INSERT INTO "ingredients" ("name", "user_id")
VALUES
('5 spice powder', NULL),
('acorn squash', NULL),
('adobo sauce', NULL),
('agave nectar', NULL),
('ahi tuna', NULL),
('alfredo pasta sauce', NULL),
('almond extract', NULL),
('almond flour', NULL),
('almond milk', NULL),
('almonds', NULL),
('amaretto', NULL),
('ancho chiles', NULL),
('anchovies', NULL),
('andouille sausage', NULL),
('angel food cake mix', NULL),
('angel hair pasta', NULL),
('angostura bitters', NULL),
('apple', NULL),
('apple butter spread', NULL),
('apple cider', NULL),
('apple juice', NULL),
('apple pie spice', NULL),
('apricot preserves', NULL),
('apricots', NULL),
('arborio rice', NULL),
('arrowroot powder', NULL),
('artichoke heart quarters', NULL),
('artichokes', NULL),
('arugula', NULL),
('asafoetida', NULL),
('asafoetida powder', NULL),
('asiago cheese', NULL),
('asian pear', NULL),
('asparagus spears', NULL),
('avocado', NULL),
('avocado oil', NULL),
('baby bell peppers', NULL),
('baby bok choy', NULL),
('baby carrots', NULL),
('baby corn', NULL),
('baby spinach leaves', NULL),
('baby-back ribs', NULL),
('bacon', NULL),
('bacon fat', NULL),
('baguette', NULL),
('baking bar', NULL),
('baking powder', NULL),
('baking soda', NULL),
('balsamic glaze', NULL),
('balsamic vinegar', NULL),
('bamboo shoots', NULL),
('banana', NULL),
('basmati rice', NULL),
('bay leaves', NULL),
('bbq sauce', NULL),
('beans', NULL),
('beef', NULL),
('beef brisket', NULL),
('beef broth', NULL),
('beef chuck roast', NULL),
('beef stock', NULL),
('beef tenderloin', NULL),
('beer', NULL),
('beets', NULL),
('bell pepper', NULL),
('berries', NULL),
('biscuit mix', NULL),
('biscuits', NULL),
('bittersweet chocolate', NULL),
('black bean sauce', NULL),
('black beans', NULL),
('black olives', NULL),
('black pepper', NULL),
('black sesame seeds', NULL),
('blackberries', NULL),
('blanched almonds', NULL),
('blood orange', NULL),
('blue cheese', NULL),
('blueberries', NULL),
('bok choy', NULL),
('boneless skinless chicken breast', NULL),
('bourbon', NULL),
('brandy', NULL),
('bread', NULL),
('bread flour', NULL),
('breakfast links', NULL),
('brie', NULL),
('broccoli', NULL),
('broccoli florets', NULL),
('brown rice', NULL),
('brown rice flour', NULL),
('brown sugar', NULL),
('brownie mix', NULL),
('brussel sprouts', NULL),
('bulgur', NULL),
('butter', NULL),
('butterhead lettuce', NULL),
('buttermilk', NULL),
('butternut squash', NULL),
('butterscotch chips', NULL),
('cabbage', NULL),
('caesar dressing', NULL),
('cajun seasoning', NULL),
('cake flour', NULL),
('candy canes', NULL),
('candy coating', NULL),
('candy melts', NULL),
('canned black beans', NULL),
('canned diced tomatoes', NULL),
('canned garbanzo beans', NULL),
('canned green chiles', NULL),
('canned kidney beans', NULL),
('canned mushrooms', NULL),
('canned pinto beans', NULL),
('canned red kidney beans', NULL),
('canned tomatoes', NULL),
('canned tuna', NULL),
('canned white beans', NULL),
('canned white cannellini beans', NULL),
('cannellini beans', NULL),
('cantaloupe', NULL),
('capers', NULL),
('caramel sauce', NULL),
('caramels', NULL),
('caraway seed', NULL),
('cardamom', NULL),
('cardamom pods', NULL),
('carp', NULL),
('carrots', NULL),
('cat fish filets', NULL),
('cauliflower', NULL),
('cauliflower florets', NULL),
('cauliflower rice', NULL),
('celery', NULL),
('celery ribs', NULL),
('celery root', NULL),
('celery salt', NULL),
('celery seed', NULL),
('cereal', NULL),
('champagne', NULL),
('chana dal', NULL),
('cheddar', NULL),
('cheese curds', NULL),
('cheese dip', NULL),
('cheese soup', NULL),
('cheese tortellini', NULL),
('cherry', NULL),
('cherry pie filling', NULL),
('cherry tomatoes', NULL),
('chestnuts', NULL),
('chia seeds', NULL),
('chicken base', NULL),
('chicken bouillon', NULL),
('chicken bouillon granules', NULL),
('chicken breasts', NULL),
('chicken broth', NULL),
('chicken drumsticks', NULL),
('chicken legs', NULL),
('chicken pieces', NULL),
('chicken sausage', NULL),
('chicken stock', NULL),
('chicken tenders', NULL),
('chicken thighs', NULL),
('chicken wings', NULL),
('chickpea', NULL),
('chile garlic sauce', NULL),
('chili paste', NULL),
('chili peppers', NULL),
('chili powder', NULL),
('chili sauce', NULL),
('chipotle chiles in adobo', NULL),
('chipotle chilies', NULL),
('chipotle peppers in adobo', NULL),
('chive & onion cream cheese spread', NULL),
('chocolate', NULL),
('chocolate chip cookies', NULL),
('chocolate chunks', NULL),
('chocolate ice cream', NULL),
('chocolate milk', NULL),
('chocolate sandwich cookies', NULL),
('chocolate syrup', NULL),
('chocolate wafer cookies', NULL),
('chorizo sausage', NULL),
('cider vinegar', NULL),
('cilantro', NULL),
('cinnamon roll', NULL),
('cinnamon stick', NULL),
('cinnamon sugar', NULL),
('cinnamon swirl bread', NULL),
('clam juice', NULL),
('clams', NULL),
('clarified butter', NULL),
('clove', NULL),
('coarse salt', NULL),
('coarsely ground pepper', NULL),
('cocoa nibs', NULL),
('cocoa powder', NULL),
('coconut', NULL),
('coconut aminos', NULL),
('coconut butter', NULL),
('coconut cream', NULL),
('coconut extract', NULL),
('coconut flour', NULL),
('coconut milk', NULL),
('coconut oil', NULL),
('coconut water', NULL),
('cod', NULL),
('coffee', NULL),
('cognac', NULL),
('cola', NULL),
('colby jack', NULL),
('collard greens', NULL),
('condensed cream of celery soup', NULL),
('condensed cream of mushroom soup', NULL),
('confectioner''s swerve', NULL),
('cooked bacon', NULL),
('cooked brown rice', NULL),
('cooked chicken breast', NULL),
('cooked ham', NULL),
('cooked long grain rice', NULL),
('cooked pasta', NULL),
('cooked polenta', NULL),
('cooked quinoa', NULL),
('cooked wild rice', NULL),
('cookies', NULL),
('coriander', NULL),
('corn', NULL),
('corn bread mix', NULL),
('corn chips', NULL),
('corn flakes cereal', NULL),
('corn flour', NULL),
('corn kernels', NULL),
('corn oil', NULL),
('corn tortillas', NULL),
('cornbread', NULL),
('corned beef', NULL),
('cornish hens', NULL),
('cornmeal', NULL),
('cornstarch', NULL),
('cotija cheese', NULL),
('cottage cheese', NULL),
('country bread', NULL),
('courgettes', NULL),
('couscous', NULL),
('cow pea', NULL),
('crabmeat', NULL),
('cracked pepper', NULL),
('cranberries', NULL),
('cranberry juice', NULL),
('cream', NULL),
('cream cheese', NULL),
('cream cheese block', NULL),
('cream of chicken soup', NULL),
('cream of tartar', NULL),
('creamed corn', NULL),
('creamy peanut butter', NULL),
('creme fraiche', NULL),
('cremini mushrooms', NULL),
('creole seasoning', NULL),
('crisp rice cereal', NULL),
('croutons', NULL),
('crystallized ginger', NULL),
('cucumber', NULL),
('cumin seeds', NULL),
('cup cake', NULL),
('currants', NULL),
('curry leaves', NULL),
('dairy free milk', NULL),
('dark brown sugar', NULL),
('dark chocolate', NULL),
('dark chocolate candy bars', NULL),
('dark chocolate chips', NULL),
('dark sesame oil', NULL),
('dates', NULL),
('deep dish pie crust', NULL),
('deli ham', NULL),
('deli turkey', NULL),
('dessert oats', NULL),
('dessert wine', NULL);
INSERT INTO ingredients (name, user_id)
VALUES
('diced ham', null),
('diet pop', null),
('dijon mustard', null),
('dill', null),
('dill pickles', null),
('hot dog', null),
('double cream', null),
('dried apricots', null),
('dried basil', null),
('dried cherries', null),
('dried chorizo', null),
('dried cranberries', null),
('dried dill', null),
('dried onion', null),
('dried porcini mushrooms', null),
('dried rubbed sage', null),
('dried thyme', null),
('dried tomatoes', null),
('dry bread crumbs', null),
('dry milk', null),
('dry mustard', null),
('dry red wine', null),
('dry roasted peanuts', null),
('duck fat', null),
('dutch process cocoa powder', null),
('edamame', null),
('egg substitute', null),
('egg vermicelli', null),
('egg whites', null),
('egg yolk', null),
('eggnog', null),
('eggplant', null),
('elbow macaroni', null),
('enchilada sauce', null),
('english cucumber', null),
('english muffin', null),
('erythritol', null),
('escarole', null),
('espresso', null),
('evaporated milk', null),
('extra firm tofu', null),
('extra virgin olive oil', null),
('farfalle', null),
('farro', null),
('fat free mayo', null),
('fat-free less-sodium chicken broth', null),
('fennel', null),
('fennel seeds', null),
('fenugreek leaf', null),
('fenugreek seeds', null),
('feta cheese', null),
('fettuccine', null),
('fire roasted tomatoes', null),
('fish', null),
('fish sauce', null),
('fish stock', null),
('flank steak', null),
('flax seeds', null),
('fleur de sel', null),
('flour', null),
('flour tortillas', null),
('fontina cheese', null),
('food dye', null),
('franks redhot sauce', null),
('free range eggs', null),
('french bread', null),
('fresh basil', null),
('fresh bean sprouts', null),
('fresh chives', null),
('fresh corn', null),
('fresh corn kernels', null),
('fresh figs', null),
('fresh fruit', null),
('fresh herbs', null),
('fresh mint', null),
('fresh mozzarella', null),
('fresh rosemary', null),
('fresh thyme leaves', null),
('fried onions', null),
('frosting', null),
('froyo bars', null),
('frozen corn', null),
('frozen spinach', null),
('fudge', null),
('fudge topping', null),
('fun size almond joy bar', null),
('garam masala', null),
('garbanzo bean flour', null),
('garlic', null),
('garlic paste', null),
('garlic powder', null),
('garlic salt', null),
('gelatin', null),
('gf chocolate cake mix', null),
('gin', null),
('ginger', null),
('ginger ale', null),
('ginger paste', null),
('ginger-garlic paste', null),
('gingersnap cookies', null),
('gnocchi', null),
('goat cheese', null),
('golden raisins', null),
('gorgonzola', null),
('gouda cheese', null),
('graham cracker crumbs', null),
('graham cracker pie crust', null),
('graham crackers', null),
('grain blend', null),
('grand marnier', null),
('granny smith apples', null),
('granola', null),
('granulated garlic', null),
('grape tomatoes', null),
('grapefruit', null),
('grapeseed oil', null),
('gravy', null),
('great northern beans', null),
('greek yogurt', null),
('green beans', null),
('green bell pepper', null),
('green chili pepper', null),
('green food coloring', null),
('green grapes', null),
('green olives', null),
('green onions', null),
('greens', null),
('grill cheese', null),
('grill seasoning', null),
('ground allspice', null),
('ground ancho chili', null),
('ground beef', null),
('ground chicken', null),
('ground chipotle chile pepper', null),
('ground cinnamon', null),
('ground cloves', null),
('ground coriander seeds', null),
('ground cumin', null),
('ground flaxseed', null),
('ground ginger', null),
('ground lamb', null),
('ground mace', null),
('ground nutmeg', null),
('ground pork', null),
('ground pork sausage', null),
('ground veal', null),
('gruyere', null),
('guacamole', null),
('half n half', null),
('halibut fillet', null),
('ham', null),
('hamburger buns', null),
('hard cooked eggs', null),
('harissa', null),
('hash brown potatoes', null),
('hazelnuts', null),
('healthy request cream of celery soup', null),
('hemp seeds', null),
('herbes de provence', null),
('herbs', null),
('hersheys kisses brand milk chocolates', null),
('hoisin sauce', null),
('honey mustard', null),
('horseradish', null),
('hot sauce', null),
('hummus', null),
('ice', null),
('ice cream', null),
('instant chocolate pudding mix', null),
('instant coffee powder', null),
('instant espresso powder', null),
('instant lemon pudding mix', null),
('instant yeast', null),
('irish cream', null),
('italian bread', null),
('italian cheese blend', null),
('italian sausages', null),
('italian seasoning', null),
('jaggery', null),
('jalapeno', null),
('jasmine rice', null),
('jelly', null),
('jicama', null),
('jimmies', null),
('juice', null),
('jumbo shell pasta', null),
('kaffir lime leaves', null),
('kahlua', null),
('kalamata olives', null),
('kale', null),
('ketchup', null),
('kitchen bouquet', null),
('kiwis', null),
('kosher salt', null),
('ladyfingers', null),
('lamb', null),
('lasagna noodles', null),
('lb cake', null),
('lean ground beef', null),
('lean ground turkey', null),
('lean pork tenderloin', null),
('leeks', null),
('leg of lamb', null),
('lemon', null),
('lemon curd', null),
('lemon extract', null),
('lemon juice', null),
('lemon peel', null),
('lemon pepper', null),
('lemon wedges', null),
('lemongrass', null),
('lettuce', null),
('lettuce leaves', null),
('light butter', null),
('light coconut milk', null),
('light corn syrup', null),
('light cream cheese', null),
('light mayonnaise', null),
('light olive oil', null),
('light soy sauce', null),
('lime', null),
('lime juice', null),
('lime wedges', null),
('lime zest', null),
('linguine', null),
('liquid smoke', null),
('liquid stevia', null),
('liquor', null),
('live lobster', null),
('long-grain rice', null),
('low fat buttermilk', null),
('low fat milk', null),
('low fat plain yogurt', null),
('low fat ricotta cheese', null),
('low fat sour cream', null),
('low sodium chicken broth', null),
('low sodium soy sauce', null),
('low-sodium chicken stock', null),
('lower sodium beef broth', null),
('lump crab', null),
('m&m candies', null),
('macadamia nuts', null),
('macaroni and cheese mix', null),
('madras curry powder', null),
('malt drink mix', null),
('mandarin orange sections', null),
('mandarin oranges', null),
('mango', null),
('maple syrup', null),
('maraschino cherries', null),
('margarine', null),
('marinara sauce', null),
('marjoram', null),
('marsala wine', null),
('marshmallow fluff', null),
('marshmallows', null),
('masa harina', null),
('mascarpone', null),
('mat beans', null),
('matcha tea', null),
('mayonnaise', null),
('meat', null),
('meatballs', null),
('medjool dates', null),
('mexican cream', null),
('meyer lemon juice', null),
('milk', null),
('milk chocolate chips', null),
('mint chutney', null),
('minute rice', null),
('miracle whip', null),
('mirin', null),
('miso', null),
('molasses', null),
('monterey jack cheese', null),
('mushroom', null),
('mussels', null);
INSERT INTO ingredients (name, user_id)
VALUES
('mustard', NULL),
('mustard seeds', NULL),
('napa cabbage', NULL),
('navel oranges', NULL),
('nectarine', NULL),
('new potatoes', NULL),
('non-fat greek yogurt', NULL),
('nonfat cool whip', NULL),
('nonfat milk', NULL),
('nori', NULL),
('nut butter', NULL),
('nut meal', NULL),
('nutella', NULL),
('nutritional yeast', NULL),
('oat flour', NULL),
('oats', NULL),
('oil', NULL),
('oil packed sun dried tomatoes', NULL),
('okra', NULL),
('old bay seasoning', NULL),
('olive oil', NULL),
('olives', NULL),
('onion', NULL),
('onion powder', NULL),
('onion soup mix', NULL),
('orange', NULL),
('orange bell pepper', NULL),
('orange juice', NULL),
('orange juice concentrate', NULL),
('orange liqueur', NULL),
('orange marmalade', NULL),
('orange oil', NULL),
('orange zest', NULL),
('oregano', NULL),
('oreo cookies', NULL),
('orzo', NULL),
('oyster sauce', NULL),
('oysters', NULL),
('palm sugar', NULL),
('pancetta', NULL),
('paneer', NULL),
('panko', NULL),
('papaya', NULL),
('paprika', NULL),
('parmigiano reggiano', NULL),
('parsley', NULL),
('parsley flakes', NULL),
('parsnip', NULL),
('part-skim mozzarella cheese', NULL),
('pasta', NULL),
('pasta salad mix', NULL),
('pasta sauce', NULL),
('pastry flour', NULL),
('peach', NULL),
('peanut butter', NULL),
('peanut butter chips', NULL),
('peanut butter cups', NULL),
('peanut oil', NULL),
('peanuts', NULL),
('pear liqueur', NULL),
('pearl barley', NULL),
('pearl onions', NULL),
('peas', NULL),
('pecan', NULL),
('pecan pieces', NULL),
('pecorino', NULL),
('penne', NULL),
('peperoncino', NULL),
('pepper jack cheese', NULL),
('peppercorns', NULL),
('peppermint baking chips', NULL),
('peppermint extract', NULL),
('pepperoni', NULL),
('peppers', NULL),
('pesto', NULL),
('pickle relish', NULL),
('pickles', NULL),
('pico de gallo', NULL),
('pie crust', NULL),
('pimento stuffed olives', NULL),
('pimientos', NULL),
('pine nuts', NULL),
('pineapple', NULL),
('pineapple chunks', NULL),
('pineapple in juice', NULL),
('pineapple juice', NULL),
('pink himalayan salt', NULL),
('pinto beans', NULL),
('pistachios', NULL),
('pita', NULL),
('pizza crust', NULL),
('pizza mix', NULL),
('plain greek yogurt', NULL),
('plain nonfat yogurt', NULL),
('plain yogurt', NULL),
('plantain', NULL),
('plum', NULL),
('plum tomatoes', NULL),
('poblano peppers', NULL),
('polenta', NULL),
('polish sausage', NULL),
('pomegranate juice', NULL),
('pomegranate molasses', NULL),
('pomegranate seeds', NULL),
('popcorn', NULL),
('poppy seeds', NULL),
('pork', NULL),
('Pork & Beans', NULL),
('pork belly', NULL),
('pork butt', NULL),
('pork chops', NULL),
('pork links', NULL),
('pork loin chops', NULL),
('pork loin roast', NULL),
('pork roast', NULL),
('pork shoulder', NULL),
('pork tenderloin', NULL),
('port', NULL),
('portabella mushrooms', NULL),
('pot roast', NULL),
('potato chips', NULL),
('potato starch', NULL),
('potatoes', NULL),
('poultry seasoning', NULL),
('powdered sugar', NULL),
('pretzel sandwiches', NULL),
('processed american cheese', NULL),
('prosciutto', NULL),
('provolone cheese', NULL),
('prunes', NULL),
('puff pastry', NULL),
('pumpkin', NULL),
('pumpkin pie filling', NULL),
('pumpkin pie spice', NULL),
('pumpkin puree', NULL),
('pumpkin seeds', NULL),
('queso fresco', NULL),
('quick cooking oats', NULL),
('quinoa', NULL),
('quinoa flour', NULL),
('radicchio', NULL),
('radishes', NULL),
('raisins', NULL),
('rajma masala', NULL),
('ramen noodles', NULL),
('ranch dressing', NULL),
('ranch dressing mix', NULL),
('raspberries', NULL),
('raspberry jam', NULL),
('raw cashews', NULL),
('raw shrimp', NULL),
('ready-to-serve Asian fried rice', NULL),
('real bacon recipe pieces', NULL),
('red apples', NULL),
('red bell peppers', NULL),
('red cabbage', NULL),
('red chilli', NULL),
('red delicious apples', NULL),
('red food coloring', NULL),
('red grapefruit juice', NULL),
('red grapes', NULL),
('red kidney beans', NULL),
('red lentils', NULL),
('red onion', NULL),
('red pepper flakes', NULL),
('red pepper powder', NULL),
('red potatoes', NULL),
('red velvet cookie', NULL),
('red wine', NULL),
('red wine vinegar', NULL),
('reduced fat shredded cheddar cheese', NULL),
('refried beans', NULL),
('refrigerated crescent rolls', NULL),
('refrigerated pizza dough', NULL),
('refrigerated sugar cookie dough', NULL),
('rhubarb', NULL),
('rib tips', NULL),
('rice', NULL),
('rice flour', NULL),
('rice krispies cereal', NULL),
('rice milk', NULL),
('rice noodles', NULL),
('rice paper', NULL),
('rice syrup', NULL),
('rice vinegar', NULL),
('rice wine', NULL),
('ricotta salata', NULL),
('ritz crackers', NULL),
('roast beef', NULL),
('roasted chicken', NULL),
('roasted nuts', NULL),
('roasted peanuts', NULL),
('roasted red peppers', NULL),
('roma tomatoes', NULL),
('romaine lettuce', NULL),
('root vegetables', NULL),
('rosemary', NULL),
('rotini pasta', NULL),
('rotisserie chicken', NULL),
('round steak', NULL),
('rub', NULL),
('rum extract', NULL),
('runny honey', NULL),
('russet potatoes', NULL),
('rutabaga', NULL),
('rye bread', NULL),
('rye meal', NULL),
('saffron threads', NULL),
('sage', NULL),
('sage leaves', NULL),
('salad dressing', NULL),
('salami', NULL),
('salmon fillet', NULL),
('salsa', NULL),
('salsa verde', NULL),
('salt', NULL),
('salt and pepper', NULL),
('salted butter', NULL),
('saltine crackers', NULL),
('sandwich bun', NULL),
('sauerkraut', NULL),
('sausage', NULL),
('sausage links', NULL),
('scotch bonnet chili', NULL),
('sea salt', NULL),
('sea scallops', NULL),
('seasoned bread crumbs', NULL),
('seasoned rice vinegar', NULL),
('seasoned salt', NULL),
('seasoning', NULL),
('seasoning blend', NULL),
('seeds', NULL),
('self-rising flour', NULL),
('semi sweet chocolate chips', NULL),
('serrano chile', NULL),
('sesame oil', NULL),
('sesame seed hamburger buns', NULL),
('sesame seeds', NULL),
('shallot', NULL),
('sharp cheddar cheese', NULL),
('sheeps milk cheese', NULL),
('shells', NULL),
('sherry', NULL),
('sherry vinegar', NULL),
('shiitake mushroom caps', NULL),
('short grain rice', NULL),
('short pasta', NULL),
('short ribs', NULL),
('shortbread cookies', NULL),
('shortcrust pastry', NULL),
('shortening', NULL),
('shredded cheddar cheese', NULL),
('shredded cheese', NULL),
('shredded chicken', NULL),
('shredded coconut', NULL),
('shredded mexican cheese blend', NULL),
('shredded mozzarella', NULL),
('silken tofu', NULL),
('sirloin steak', NULL),
('skim milk ricotta', NULL),
('skim vanilla greek yogurt', NULL),
('skin-on bone-in chicken leg quarters', NULL),
('skinless boneless chicken breast halves', NULL),
('skinless boneless chicken thighs', NULL),
('skinned black gram', NULL),
('slaw dressing', NULL),
('slaw mix', NULL),
('slivered almonds', NULL),
('smoked paprika', NULL),
('smoked salmon', NULL),
('smoked sausage', NULL),
('smooth peanut butter', NULL),
('snapper fillets', NULL),
('snow peas', NULL),
('soda water', NULL),
('sour cream', NULL),
('sourdough bowl', NULL),
('sourdough bread', NULL);
INSERT INTO ingredients (name, user_id) VALUES
('soy milk', null),
('soy protein powder', null),
('soy sauce', null),
('spaghetti', null),
('spaghetti squash', null),
('sparkling wine', null),
('spelt flour', null),
('spicy brown mustard', null),
('spinach', null),
('sprite', null),
('sprouts', null),
('squash', null),
('sriracha sauce', null),
('steaks', null),
('steel cut oats', null),
('stevia', null),
('stew meat', null),
('stew vegetables', null),
('stock', null),
('store-bought phyllo', null),
('stout', null),
('strawberries', null),
('strawberry jam', null),
('strawberry jello', null),
('stuffing', null),
('stuffing mix', null),
('sub rolls', null),
('sugar', null),
('sugar snap peas', null),
('sugar syrup', null),
('sukrin sweetener', null),
('summer savory', null),
('summer squash', null),
('sunflower oil', null),
('sunflower seeds', null),
('sweet chilli sauce', null),
('sweet onion', null),
('sweet paprika', null),
('sweet pickle juice', null),
('sweet pickle relish', null),
('sweet potato', null),
('sweet tea', null),
('sweetened coconut', null),
('sweetened condensed milk', null),
('sweetened shredded coconut', null),
('swiss chard', null),
('swiss cheese', null),
('taco seasoning mix', null),
('taco shells', null),
('tahini', null),
('tamari', null),
('tapioca flour', null),
('tarragon', null),
('tart apple', null),
('tea bags', null),
('tequila', null),
('teriyaki sauce', null),
('thai basil', null),
('thai chiles', null),
('thai red curry paste', null),
('thick-cut bacon', null),
('tilapia fillets', null),
('toast', null),
('toffee bits', null),
('tofu', null),
('tomatillos', null),
('tomato juice', null),
('tomato paste', null),
('tomato puree', null),
('tomato sauce', null),
('tomato soup', null),
('tomatoes', null),
('top blade steak', null),
('top round steak', null),
('Top Sirloin', null),
('tortilla', null),
('tortilla chips', null),
('triple sec', null),
('truffle oil', null),
('tuna', null),
('turbinado sugar', null),
('turkey', null),
('turkey breast', null),
('turkey kielbasa', null),
('turmeric', null),
('turnips', null),
('unbleached flour', null),
('unsalted butter', null),
('unsmoked back bacon', null),
('unsweetened applesauce', null),
('unsweetened coconut milk', null),
('unsweetened shredded coconut', null),
('vanilla bean', null),
('vanilla bean paste', null),
('vanilla essence', null),
('vanilla extract', null),
('vanilla frosting', null),
('vanilla instant pudding mix', null),
('vanilla protein powder', null),
('vanilla wafers', null),
('vanilla yogurt', null),
('vegan cheese', null),
('vegan chocolate chips', null),
('vegan margarine', null),
('vegetable broth', null),
('vegetable oil', null),
('vegetarian bacon', null),
('vermouth', null),
('vinaigrette', null),
('vinegar', null),
('vodka', null),
('walnuts', null),
('water', null),
('water chestnuts', null),
('water-packed tuna', null),
('watercress', null),
('watermelon chunks', null),
('wheat bran', null),
('wheat germ', null),
('whipped cream', null),
('whipped topping', null),
('whipping cream', null),
('whiskey', null),
('white balsamic vinegar', null),
('white bread', null),
('white cake mix', null),
('white cheddar', null),
('white chocolate', null),
('white chocolate chips', null),
('white onion', null),
('white pepper', null),
('white whole wheat flour', null),
('white wine', null),
('white wine vinegar', null),
('whole allspice berries', null),
('whole chicken', null),
('whole coriander seeds', null),
('whole cranberry sauce', null),
('whole kernel corn', null),
('whole star anise', null),
('whole wheat bread', null),
('whole wheat flour', null),
('whole wheat tortillas', null),
('whole-grain mustard', null),
('wine', null),
('wine vinegar', null),
('winter squash', null),
('won ton wraps', null),
('worcestershire sauce', null),
('wraps', null),
('xanthan gum', null),
('yeast', null),
('yellow bell pepper', null),
('yellow cake mix', null),
('yellow onion', null),
('yogurt', null),
('yukon gold potato', null);
