INSERT INTO "ingredients" ("name", "measurement") VALUES 
('Salt', 'teaspoon'),
('Sugar', 'cup'),
('Flour', 'cup'),
('Olive Oil', 'tablespoon'),
('Butter', 'tablespoon'),
('Milk', 'cup'),
('Eggs', 'count'),
('Baking Powder', 'teaspoon'),
('Baking Soda', 'teaspoon'),
('Vanilla Extract', 'teaspoon'),
('Cinnamon', 'teaspoon'),
('Nutmeg', 'teaspoon'),
('Ginger', 'teaspoon'),
('Garlic', 'clove'),
('Onion', 'count'),
('Black Pepper', 'teaspoon'),
('Paprika', 'teaspoon'),
('Cumin', 'teaspoon'),
('Chili Powder', 'teaspoon'),
('Oregano', 'teaspoon'),
('Thyme', 'teaspoon'),
('Rosemary', 'teaspoon'),
('Basil', 'teaspoon'),
('Parsley', 'teaspoon'),
('Bay Leaves', 'count'),
('Soy Sauce', 'tablespoon'),
('Honey', 'tablespoon'),
('Ketchup', 'tablespoon'),
('Mustard', 'teaspoon'),
('Mayonnaise', 'tablespoon'),
('Vinegar', 'tablespoon'),
('Rice', 'cup'),
('Pasta', 'cup'),
('Bread', 'slice'),
('Cheese', 'cup'),
('Chicken Breast', 'count'),
('Ground Beef', 'pound'),
('Pork Chops', 'count'),
('Fish Fillet', 'count'),
('Shrimp', 'count'),
('Broccoli', 'cup'),
('Carrots', 'count'),
('Tomatoes', 'count'),
('Lettuce', 'cup'),
('Bell Peppers', 'count'),
('Potatoes', 'count'),
('Sweet Potatoes', 'count'),
('Spinach', 'cup'),
('Mushrooms', 'cup'),
('Zucchini', 'count'),
('Cucumber', 'count'),
('Corn', 'cup'),
('Peas', 'cup'),
('Green Beans', 'cup'),
('Avocado', 'count'),
('Apple', 'count'),
('Banana', 'count'),
('Orange', 'count'),
('Strawberries', 'cup'),
('Blueberries', 'cup'),
('Grapes', 'cup'),
('Lemon', 'count'),
('Lime', 'count'),
('Pineapple', 'cup'),
('Mango', 'count'),
('Watermelon', 'cup'),
('Coconut Milk', 'cup'),
('Almonds', 'cup'),
('Walnuts', 'cup'),
('Peanut Butter', 'tablespoon'),
('Jelly', 'tablespoon'),
('Chickpeas', 'cup'),
('Black Beans', 'cup'),
('Kidney Beans', 'cup'),
('Lentils', 'cup'),
('Tofu', 'ounce'),
('Cottage Cheese', 'cup'),
('Yogurt', 'cup'),
('Cream Cheese', 'tablespoon'),
('Heavy Cream', 'cup'),
('Sour Cream', 'cup'),
('Cornmeal', 'cup'),
('Oats', 'cup'),
('Quinoa', 'cup'),
('Barley', 'cup'),
('Couscous', 'cup'),
('Bread Crumbs', 'cup'),
('Chicken Broth', 'cup'),
('Beef Broth', 'cup'),
('Vegetable Broth', 'cup'),
('Tomato Sauce', 'cup'),
('Tomato Paste', 'tablespoon'),
('Diced Tomatoes', 'cup'),
('Tomato Juice', 'cup'),
('Pasta Sauce', 'cup'),
('Salsa', 'cup'),
('Hot Sauce', 'teaspoon'),
('Maple Syrup', 'tablespoon'),
('Molasses', 'tablespoon'),
('Brown Sugar', 'cup'),
('Powdered Sugar', 'cup'),
('Confectioner Sugar', 'cup'),
('Cocoa Powder', 'tablespoon'),
('Chocolate Chips', 'cup'),
('Baking Chocolate', 'ounce'),
('Marshmallows', 'cup'),
('Coconut Flakes', 'cup'),
('Evaporated Milk', 'cup'),
('Condensed Milk', 'cup'),
('Ice Cream', 'cup'),
('Whipped Cream', 'cup'),
('Gelatin', 'teaspoon'),
('Pudding Mix', 'ounce'),
('Pie Crust', 'count'),
('Pastry Dough', 'count'),
('Pizza Dough', 'count'),
('Phyllo Dough', 'count'),
('Puff Pastry', 'count'),
('Yeast', 'teaspoon'),
('Cornstarch', 'tablespoon'),
('Arrowroot Powder', 'tablespoon'),
('Tapioca Starch', 'tablespoon'),
('Agar Agar', 'teaspoon'),
('Gelatin Sheets', 'count'),
('Almond Flour', 'cup'),
('Coconut Flour', 'cup'),
('Whole Wheat Flour', 'cup'),
('Rice Flour', 'cup'),
('Cake Flour', 'cup'),
('Bread Flour', 'cup'),
('Self-Rising Flour', 'cup'),
('Corn Flour', 'cup'),
('Polenta', 'cup'),
('Grits', 'cup'),
('Bread Mix', 'cup'),
('Pancake Mix', 'cup'),
('Waffle Mix', 'cup'),
('Muffin Mix', 'cup'),
('Cake Mix', 'cup'),
('Brownie Mix', 'cup'),
('Cornbread Mix', 'cup'),
('Pasta Noodles', 'cup'),
('Ramen Noodles', 'count'),
('Rice Noodles', 'cup'),
('Egg Noodles', 'cup'),
('Cabbage', 'cup'),
('Cauliflower', 'cup'),
('Brussels Sprouts', 'cup'),
('Asparagus', 'cup'),
('Artichoke', 'count'),
('Eggplant', 'count'),
('Beets', 'count'),
('Radishes', 'count'),
('Turnips', 'count'),
('Parsnips', 'count'),
('Kale', 'cup'),
('Collard Greens', 'cup'),
('Swiss Chard', 'cup'),
('Bok Choy', 'cup'),
('Leeks', 'count'),
('Shallots', 'count'),
('Scallions', 'count'),
('Chives', 'tablespoon'),
('Mint', 'tablespoon'),
('Cilantro', 'tablespoon'),
('Dill', 'tablespoon'),
('Tarragon', 'tablespoon'),
('Sage', 'teaspoon'),
('Fennel', 'count'),
('Turmeric', 'teaspoon'),
('Cardamom', 'teaspoon'),
('Cloves', 'teaspoon'),
('Allspice', 'teaspoon'),
('Star Anise', 'count'),
('Sesame Seeds', 'tablespoon'),
('Chia Seeds', 'tablespoon'),
('Flax Seeds', 'tablespoon'),
('Pumpkin Seeds', 'cup'),
('Sunflower Seeds', 'cup'),
('Tahini', 'tablespoon'),
('Hummus', 'cup'),
('Sriracha', 'teaspoon'),
('BBQ Sauce', 'tablespoon'),
('Ranch Dressing', 'tablespoon'),
('Caesar Dressing', 'tablespoon'),
('Blue Cheese Dressing', 'tablespoon'),
('Italian Dressing', 'tablespoon'),
('French Dressing', 'tablespoon'),
('Vinaigrette', 'tablespoon'),
('Coconut Oil', 'tablespoon'),
('Vegetable Oil', 'tablespoon'),
('Canola Oil', 'tablespoon'),
('Peanut Oil', 'tablespoon'),
('Sesame Oil', 'teaspoon'),
('Ghee', 'tablespoon'),
('Lard', 'tablespoon'),
('Shortening', 'tablespoon'),
('Margarine', 'tablespoon'),
('Cream of Tartar', 'teaspoon'),
('Balsamic Vinegar', 'tablespoon'),
('Red Wine Vinegar', 'tablespoon'),
('White Wine Vinegar', 'tablespoon'),
('Apple Cider Vinegar', 'tablespoon'),
('Rice Vinegar', 'tablespoon'),
('Worcestershire Sauce', 'teaspoon'),
('Fish Sauce', 'teaspoon'),
('Hoisin Sauce', 'tablespoon'),
('Oyster Sauce', 'tablespoon'),
('Miso Paste', 'tablespoon');

