INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('5 spice powder', 1002002, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('acorn squash', 11482, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('adobo sauce', 6979, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('agave nectar', 19912, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('ahi tuna', 15117, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('alfredo pasta sauce', 93606, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('almond extract', 1002050, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('almond flour', 93740, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('almond milk', 93607, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('almonds', 12061, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('amaretto', 10014534, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('ancho chiles', 10211962, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('anchovies', 15001, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('andouille sausage', 7064, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('angel food cake mix', 18087, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('angel hair pasta', 10020420, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('angostura bitters', 93653, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('apple', 9003, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('apple butter spread', 19294, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('apple cider', 1009016, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('apple juice', 9016, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('apple pie spice', 1042035, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('apricot preserves', 19719, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('apricots', 9021, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('arborio rice', 10020052, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('arrowroot powder', 20003, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('artichoke heart quarters', 93828, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('artichokes', 11007, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('arugula', 11959, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('asafoetida', 1032035, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('asafoetida powder', 0, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('asiago cheese', 1001033, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('asian pear', 9252, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('asparagus spears', 11011, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('avocado', 9037, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('avocado oil', 4581, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('baby bell peppers', 10311821, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('baby bok choy', 93636, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('baby carrots', 11960, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('baby corn', 10011168, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('baby spinach leaves', 11457, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('baby-back ribs', 10010204, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('baby-back ribs', 10192, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('bacon', 10123, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('bacon fat', 4609, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('baguette', 18033, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('baking bar', 19078, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('baking powder', 18371, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('baking soda', 18372, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('balsamic glaze', 98998, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('balsamic vinegar', 2069, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('bamboo shoots', 11028, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('banana', 9040, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('basmati rice', 10020444, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('bay leaves', 2004, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('bbq sauce', 6150, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('beans', 16069, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('beef', 23572, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('beef brisket', 13023, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('beef broth', 6008, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('beef chuck roast', 13786, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('beef stock', 6170, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('beef tenderloin', 13926, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('beer', 14003, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('beer', 14006, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('beets', 11080, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('bell pepper', 10211821, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('berries', 1009054, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('biscuit mix', 18010, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('biscuits', 18009, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('bittersweet chocolate', 19903, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('black bean sauce', 99210, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('black beans', 16015, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('black olives', 1059195, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('black pepper', 1002030, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('black sesame seeds', 10012023, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('blackberries', 9042, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('blanched almonds', 12062, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('blood orange', 1009200, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('blue cheese', 1004, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('blueberries', 9050, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('bok choy', 11116, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('boneless skinless chicken breast', 1055062, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('bourbon', 10014037, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('brandy', 10114037, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('bread', 18064, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('bread flour', 10120129, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('breakfast links', 7919, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('brie', 1006, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('broccoli', 11090, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('broccoli florets', 10011090, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('brown rice', 20040, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('brown rice flour', 20090, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('brown sugar', 19334, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('brownie mix', 18632, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('brussel sprouts', 11098, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('bulgur', 20012, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('butter', 1001, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('butterhead lettuce', 11250, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('buttermilk', 1230, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('butternut squash', 11485, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('butterscotch chips', 19070, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('cabbage', 11109, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('caesar dressing', 43015, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('cajun seasoning', 1032028, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('cake flour', 10020129, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('candy canes', 93759, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('candy coating', 98857, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('candy melts', 93775, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('canned black beans', 16018, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('canned diced tomatoes', 11531, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('canned garbanzo beans', 16058, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('canned green chiles', 11980, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('canned kidney beans', 16034, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('canned mushrooms', 11264, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('canned pinto beans', 16044, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('canned red kidney beans', 10016034, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('canned tomatoes', 10011693, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('canned tuna', 10115121, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('canned white beans', 16051, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('canned white cannellini beans', 10016051, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('cannellini beans', 10716050, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('cantaloupe', 9181, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('capers', 2054, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('caramel sauce', 19364, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('caramels', 19074, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('caraway seed', 2005, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('cardamom', 2006, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('cardamom pods', 1002006, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('carp', 15008, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('carrots', 11124, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('cat fish filets', 15010, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('cauliflower', 11135, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('cauliflower florets', 10011135, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('cauliflower rice', 10111135, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('celery', 11143, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('celery ribs', 10111143, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('celery root', 11141, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('celery salt', 1052047, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('celery seed', 2007, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('cereal', 8029, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('champagne', 10043155, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('chana dal', 99236, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('cheddar', 1009, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('cheese', 1041009, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('cheese curds', 98921, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('cheese dip', 1188, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('cheese soup', 6038, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('cheese tortellini', 10093727, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('cherry', 9070, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('cherry pie filling', 19314, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('cherry tomatoes', 10311529, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('chestnuts', 12098, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('chia seeds', 12006, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('chicken base', 6080, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('chicken bouillon', 6480, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('chicken bouillon granules', 1006080, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('chicken breasts', 5062, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('chicken broth', 6194, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('chicken drumsticks', 5066, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('chicken legs', 5075, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('chicken pieces', 1005006, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('chicken sausage', 93668, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('chicken stock', 6172, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('chicken tenders', 1015062, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('chicken thighs', 5091, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('chicken wings', 5100, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('chickpea', 16057, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('chile garlic sauce', 93749, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('chili paste', 6973, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('chili peppers', 11962, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('chili powder', 2009, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('chili sauce', 6972, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('chipotle chiles in adobo', 11632, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('chipotle chilies', 98839, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('chipotle peppers in adobo', 99223, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('chive & onion cream cheese spread', 93748, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('chocolate', 19081, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('chocolate chip cookies', 28027, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('chocolate chunks', 10419903, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('chocolate ice cream', 19270, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('chocolate milk', 1102, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('chocolate sandwich cookies', 18166, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('chocolate syrup', 14181, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('chocolate wafer cookies', 10118157, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('chorizo sausage', 7019, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('cider vinegar', 2048, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('cilantro', 11165, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('cinnamon roll', 99020, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('cinnamon stick', 1002010, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('cinnamon sugar', 10219335, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('cinnamon swirl bread', 18047, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('clam juice', 14187, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('clams', 15157, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('clarified butter', 93632, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('clove', 1002011, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('coarse salt', 1002047, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('coarsely ground pepper', 2035, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('cocoa nibs', 98846, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('cocoa powder', 19165, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('coconut', 12104, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('coconut aminos', 98929, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('coconut butter', 93746, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('coconut cream', 12115, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('coconut extract', 1032050, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('coconut flour', 93747, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('coconut milk', 12118, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('coconut oil', 4047, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('coconut water', 12119, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('cod', 15015, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('coffee', 14209, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('cognac', 10414037, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('cola', 14400, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('colby jack', 1011, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('collard greens', 11161, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('condensed cream of celery soup', 6010, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('condensed cream of mushroom soup', 6147, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('confectioner''s swerve', 99084, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('cooked bacon', 10862, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('cooked brown rice', 20041, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('cooked chicken breast', 5064, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('cooked ham', 10802, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('cooked long grain rice', 10220445, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('cooked pasta', 20421, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('cooked polenta', 1008166, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('cooked quinoa', 20137, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('cooked wild rice', 20088, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('cookies', 10118192, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('coriander', 2012, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('corn', 11168, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('corn bread mix', 18022, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('corn chips', 19003, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('corn flakes cereal', 8020, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('corn flour', 20019, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('corn kernels', 11172, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('corn oil', 42289, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('corn tortillas', 18363, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('cornbread', 18023, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('corned beef', 13346, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('cornish hens', 5307, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('cornmeal', 35137, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('cornstarch', 20027, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('cotija cheese', 1001019, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('cottage cheese', 1012, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('country bread', 10018029, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('courgettes', 11477, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('couscous', 20028, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('cow pea', 16063, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('crabmeat', 10015136, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('cracked pepper', 2030, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('cranberries', 9078, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('cranberry juice', 43382, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('cream', 1053, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('cream cheese', 1017, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('cream cheese block', 1186, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('cream of chicken soup', 6016, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('cream of tartar', 18373, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('creamed corn', 11174, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('creamy peanut butter', 10116098, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('creme fraiche', 1001056, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('cremini mushrooms', 11266, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('creole seasoning', 1002031, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('crisp rice cereal', 8066, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('croutons', 18242, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('crystallized ginger', 93751, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('cucumber', 11206, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('cumin seeds', 2014, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('cup cake', 18139, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('currants', 9085, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('curry leaves', 93604, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('dairy free milk', 10016223, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('dark brown sugar', 10019334, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('dark chocolate', 19904, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('dark chocolate candy bars', 10019904, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('dark chocolate chips', 10019071, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('dark sesame oil', 1004058, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('dates', 9087, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('deep dish pie crust', 18945, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('deli ham', 10010151, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('deli turkey', 7259, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('dessert oats', 8121, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('dessert wine', 10014057, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('diced ham', 99186, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('diet pop', 14146, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('dijon mustard', 1002046, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('dill', 2045, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('dill pickles', 10011937, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('hot dog', 21118, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('double cream', 1011053, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('dried apricots', 9032, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('dried basil', 2003, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('dried cherries', 93822, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('dried chorizo', 99233, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('dried cranberries', 9079, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('dried dill', 2017, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('dried onion', 11284, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('dried porcini mushrooms', 10011268, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('dried rubbed sage', 1002038, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('dried thyme', 2042, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('dried tomatoes', 11955, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('dry bread crumbs', 18079, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('dry milk', 1090, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('dry mustard', 1002024, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('dry red wine', 14097, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('dry roasted peanuts', 16090, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('duck fat', 4574, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('dutch process cocoa powder', 10019165, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('edamame', 11212, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('egg substitute', 1226, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('egg vermicelli', 20409, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('egg whites', 1124, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('egg yolk', 1125, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('eggnog', 1057, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('eggplant', 11209, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('elbow macaroni', 10120499, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('enchilada sauce', 6599, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('english cucumber', 10111205, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('english muffin', 18439, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('erythritol', 98887, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('escarole', 11213, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('espresso', 14210, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('evaporated milk', 1214, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('extra firm tofu', 16163, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('extra virgin olive oil', 1034053, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('farfalle', 10120420, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('farro', 10020005, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('fat free mayo', 42193, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('fat-free less-sodium chicken broth', 6984, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('fennel', 11957, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('fennel seeds', 2018, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('fenugreek leaf', 98963, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('fenugreek seeds', 2019, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('feta cheese', 1019, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('fettuccine', 10020409, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('fire roasted tomatoes', 98849, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('fish', 10115261, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('fish sauce', 6179, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('fish stock', 6963, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('flank steak', 23657, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('flax seeds', 10012220, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('fleur de sel', 1022047, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('flour', 20081, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('flour tortillas', 10218364, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('fontina cheese', 1020, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('food dye', 10711111, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('frank''s redhot sauce', 98878, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('free range eggs', 1123, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('french bread', 18029, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('fresh basil', 2044, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('fresh bean sprouts', 11043, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('fresh chives', 11156, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('fresh corn', 11167, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('fresh corn kernels', 10011167, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('fresh figs', 9089, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('fresh fruit', 9431, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('fresh herbs', 10111297, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('fresh mint', 2064, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('fresh mozzarella', 1026, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('fresh rosemary', 2063, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('fresh thyme leaves', 2049, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('fried onions', 93709, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('frosting', 19230, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('froyo bars', 93629, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('frozen corn', 11913, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('frozen spinach', 11463, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('fudge', 19100, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('fudge topping', 10019348, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('fun size almond joy bar', 19065, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('garam masala', 93663, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('garbanzo bean flour', 16157, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('garlic', 11215, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('garlic paste', 10111215, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('garlic powder', 1022020, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('garlic powder', 2020, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('garlic salt', 1062047, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('gelatin', 19177, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('gf chocolate cake mix', 99040, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('gin', 10514037, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('ginger', 11216, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('ginger ale', 14136, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('ginger paste', 93754, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('ginger-garlic paste', 10093754, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('gingersnap cookies', 18172, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('gnocchi', 98853, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('goat cheese', 1159, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('golden raisins', 9297, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('gorgonzola', 1011004, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('gouda cheese', 1022, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('graham cracker crumbs', 10018617, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('graham cracker pie crust', 18942, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('graham crackers', 18617, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('grain blend', 10020088, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('grand marnier', 10314534, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('granny smith apples', 1089003, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('granola', 8212, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('granulated garlic', 1002020, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('grape tomatoes', 10111529, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('grapefruit', 9112, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('grapeseed oil', 4517, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('gravy', 6997, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('great northern beans', 16025, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('greek yogurt', 1256, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('green beans', 11052, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('green bell pepper', 11333, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('green chili pepper', 31015, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('green food coloring', 1441111, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('green grapes', 1019132, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('green olives', 1029195, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('green onions', 11291, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('greens', 21052, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('grill cheese', 10093624, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('grill seasoning', 1022034, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('ground allspice', 2001, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('ground ancho chili', 1022009, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('ground beef', 10023572, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('ground chicken', 5332, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('ground chipotle chile pepper', 1052009, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('ground cinnamon', 1012010, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('ground cinnamon', 2010, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('ground cloves', 2011, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('ground coriander seeds', 1002013, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('ground cumin', 1002014, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('ground flaxseed', 12220, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('ground ginger', 2021, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('ground lamb', 17224, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('ground mace', 2022, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('ground nutmeg', 2025, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('ground pork', 10219, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('ground pork sausage', 7063, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('ground veal', 17142, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('gruyere', 1023, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('guacamole', 1009037, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('half n half', 1049, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('halibut fillet', 15036, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('ham', 10151, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('hamburger buns', 18350, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('hard cooked eggs', 1129, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('harissa', 1006972, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('hash brown potatoes', 11390, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('hazelnuts', 12120, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('healthy request cream of celery soup', 6987, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('hemp seeds', 93602, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('herbes de provence', 1012042, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('herbs', 1002044, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('hershey''s kisses brand milk chocolates', 93743, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('hoisin sauce', 6175, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('honey mustard', 99227, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('horseradish', 1002055, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('hot sauce', 6168, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('hummus', 16158, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('ice', 10014412, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('ice cream', 19095, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('instant chocolate pudding mix', 19184, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('instant coffee powder', 14214, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('instant espresso powder', 10014214, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('instant lemon pudding mix', 19332, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('instant yeast', 10118375, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('irish cream', 93764, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('italian bread', 10028033, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('italian cheese blend', 93651, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('italian sausages', 7036, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('italian seasoning', 1022027, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('jaggery', 99002, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('jalapeno', 11979, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('jasmine rice', 10120444, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('jelly', 19297, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('jicama', 11603, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('jimmies', 93645, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('juice', 1019016, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('jumbo shell pasta', 10520420, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('kaffir lime leaves', 93633, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('kahlua', 93716, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('kalamata olives', 1009195, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('kale', 11233, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('ketchup', 11935, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('kitchen bouquet', 93768, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('kiwis', 9148, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('kosher salt', 1082047, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('ladyfingers', 18423, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('lamb', 10017224, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('lasagna noodles', 10620420, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('lb cake', 18133, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('lean ground beef', 23557, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('lean ground turkey', 5662, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('lean pork tenderloin', 10060, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('leeks', 11246, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('leg of lamb', 17013, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('lemon', 9150, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('lemon curd', 93834, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('lemon extract', 12311111, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('lemon juice', 9152, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('lemon peel', 9156, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('lemon pepper', 1012030, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('lemon wedges', 1029150, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('lemongrass', 11972, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('lettuce', 11252, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('lettuce leaves', 93623, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('light butter', 4602, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('light coconut milk', 99009, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('light corn syrup', 19350, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('light cream cheese', 43274, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('light mayonnaise', 4641, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('light olive oil', 1054053, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('light soy sauce', 10216124, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('lime', 9159, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('lime juice', 9160, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('lime wedges', 1029159, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('lime zest', 1009159, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('linguine', 10720420, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('liquid smoke', 93627, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('liquid stevia', 10811111, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('liquor', 14037, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('live lobster', 15147, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('long-grain rice', 10220444, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('low fat buttermilk', 1088, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('low fat milk', 1082, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('low fat milk', 1174, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('low fat plain yogurt', 1117, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('low fat ricotta cheese', 1037, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('low fat sour cream', 1179, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('low sodium chicken broth', 6970, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('low sodium soy sauce', 16424, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('low-sodium chicken stock', 1006970, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('lower sodium beef broth', 10093741, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('lump crab', 10115136, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('m&m candies', 19157, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('macadamia nuts', 12131, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('macaroni and cheese mix', 32004, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('madras curry powder', 2015, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('malt drink mix', 14311, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('mandarin orange sections', 9383, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('mandarin oranges', 9218, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('mango', 9176, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('maple syrup', 19911, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('maraschino cherries', 9328, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('margarine', 4073, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('marinara sauce', 10111549, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('marjoram', 2023, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('marsala wine', 14057, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('marshmallow fluff', 93644, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('marshmallows', 19116, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('masa harina', 20317, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('mascarpone', 93820, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('mat beans', 99144, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('matcha tea', 98932, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('mayonnaise', 4025, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('meat', 1015006, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('meat', 1065062, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('meatballs', 10110219, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('medjool dates', 9421, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('mexican cream', 93772, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('meyer lemon juice', 1009152, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('milk', 1077, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('milk chocolate chips', 10019146, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('mint chutney', 98991, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('minute rice', 20048, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('miracle whip', 4014, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('mirin', 93830, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('miso', 16112, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('molasses', 19304, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('monterey jack cheese', 1001025, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('mushroom', 11260, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('mussels', 15164, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('mustard', 2046, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('mustard seeds', 2024, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('napa cabbage', 11119, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('navel oranges', 9202, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('nectarine', 9191, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('new potatoes', 11352, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('non-fat greek yogurt', 1011256, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('nonfat cool whip', 1200, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('nonfat milk', 1085, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('nori', 11446, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('nut butter', 12195, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('nut meal', 93620, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('nutella', 19125, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('nutritional yeast', 93690, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('oat flour', 20132, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('oats', 8120, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('oil', 4582, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('oil packed sun dried tomatoes', 11956, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('okra', 11278, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('old bay seasoning', 1052034, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('olive oil', 4053, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('olives', 9195, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('onion', 11282, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('onion powder', 2026, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('onion soup mix', 6094, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('orange', 9200, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('orange bell pepper', 10011821, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('orange juice', 9206, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('orange juice concentrate', 9214, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('orange liqueur', 10414534, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('orange marmalade', 19303, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('orange oil', 12511111, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('orange zest', 9216, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('oregano', 2027, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('oreo cookies', 10018166, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('orzo', 10920420, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('oyster sauce', 6176, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('oysters', 15167, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('palm sugar', 93831, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('pancetta', 10410123, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('paneer', 98847, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('panko', 10018079, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('papaya', 9226, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('paprika', 2028, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('parmigiano reggiano', 1033, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('parsley', 11297, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('parsley flakes', 2029, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('parsnip', 11298, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('part-skim mozzarella cheese', 1028, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('pasta', 20420, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('pasta salad mix', 99036, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('pasta sauce', 10011549, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('pastry flour', 10020080, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('peach', 9236, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('peanut butter', 16098, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('peanut butter chips', 93762, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('peanut butter cups', 19150, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('peanut oil', 4042, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('peanuts', 16091, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('pear liqueur', 98988, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('pearl barley', 20005, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('pearl onions', 10111282, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('peas', 11304, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('pecan', 12142, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('pecan pieces', 10012142, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('pecorino', 1038, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('penne', 11120420, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('peperoncino', 11976, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('pepper jack cheese', 1025, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('peppercorns', 1022030, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('peppermint baking chips', 98858, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('peppermint extract', 1022050, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('pepperoni', 7057, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('peppers', 10111333, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('pesto', 93698, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('pickle relish', 11944, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('pickles', 11937, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('pico de gallo', 27027, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('pie crust', 18334, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('pimento stuffed olives', 1049195, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('pimientos', 11943, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('pine nuts', 12147, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('pineapple', 9266, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('pineapple chunks', 1029354, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('pineapple in juice', 9354, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('pineapple juice', 9273, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('pink himalayan salt', 1032047, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('pinto beans', 16043, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('pistachios', 12151, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('pita', 18413, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('pizza crust', 93770, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('pizza mix', 98924, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('plain greek yogurt', 1001256, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('plain nonfat yogurt', 1118, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('plain yogurt', 1001116, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('plantain', 9277, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('plum', 9279, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('plum tomatoes', 10411529, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('poblano peppers', 10011333, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('polenta', 10035137, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('polish sausage', 7059, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('pomegranate juice', 9442, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('pomegranate molasses', 10042040, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('pomegranate seeds', 9286, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('popcorn', 19034, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('poppy seeds', 2033, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('pork', 10010219, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('Pork & Beans', 16009, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('pork belly', 10005, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('pork butt', 10084, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('pork chops', 10010062, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('pork links', 1007063, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('pork loin chops', 10062, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('pork loin roast', 10225, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('pork roast', 10010225, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('pork shoulder', 10072, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('pork tenderloin', 10218, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('port', 10114057, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('portabella mushrooms', 11265, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('pot roast', 23612, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('potato chips', 19411, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('potato starch', 11413, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('potatoes', 11362, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('poultry seasoning', 2034, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('powdered sugar', 19336, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('pretzel sandwiches', 19047, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('processed american cheese', 1253, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('prosciutto', 10010123, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('provolone cheese', 1035, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('prunes', 9291, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('puff pastry', 18337, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('pumpkin', 11422, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('pumpkin pie filling', 11426, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('pumpkin pie spice', 1002035, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('pumpkin puree', 11424, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('pumpkin seeds', 12014, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('queso fresco', 1228, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('quick cooking oats', 8402, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('quinoa', 20035, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('quinoa flour', 93773, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('radicchio', 11952, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('radishes', 11429, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('raisins', 9299, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('rajma masala', 10193663, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('ramen noodles', 6583, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('ranch dressing', 4639, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('ranch dressing mix', 93733, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('raspberries', 9302, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('raspberry jam', 10719297, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('raw cashews', 12087, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('raw shrimp', 15152, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('ready-to-serve Asian fried rice', 93721, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('real bacon recipe pieces', 99229, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('red apples', 1079003, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('red bell peppers', 11821, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('red cabbage', 11112, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('red chilli', 11819, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('red delicious apples', 1059003, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('red food coloring', 1451111, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('red grapefruit juice', 98926, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('red grapes', 9132, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('red kidney beans', 16033, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('red lentils', 10016069, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('red onion', 10011282, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('red pepper flakes', 1032009, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('red pepper powder', 2031, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('red potatoes', 10011355, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('red velvet cookie', 18157, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('red wine', 14096, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('red wine vinegar', 1022068, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('reduced fat shredded cheddar cheese', 1001168, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('refried beans', 16202, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('refrigerated crescent rolls', 93618, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('refrigerated pizza dough', 93610, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('refrigerated sugar cookie dough', 18205, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('rhubarb', 9307, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('rib tips', 98937, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('rice', 20444, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('rice flour', 20061, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('rice krispies cereal', 8065, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('rice milk', 93761, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('rice noodles', 20133, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('rice paper', 10118368, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('rice syrup', 93784, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('rice vinegar', 1022053, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('rice wine', 43479, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('ricotta salata', 1036, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('ritz crackers', 18621, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('roast beef', 93713, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('roasted chicken', 5114, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('roasted nuts', 12135, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('roasted peanuts', 16092, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('roasted red peppers', 11916, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('roma tomatoes', 10211529, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('romaine lettuce', 10111251, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('root vegetables', 10011298, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('rosemary', 2036, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('rotini pasta', 11320420, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('rotisserie chicken', 5348, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('round steak', 23617, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('rub', 1012034, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('rum extract', 12211111, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('runny honey', 19296, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('russet potatoes', 11353, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('rutabaga', 11435, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('rye bread', 18060, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('rye meal', 98905, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('saffron threads', 2037, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('sage', 2038, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('sage leaves', 99226, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('salad dressing', 4114, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('salami', 7071, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('salmon fillet', 15076, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('salsa', 6164, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('salsa verde', 27028, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('salt', 2047, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('salt and pepper', 1102047, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('salted butter', 1001001, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('saltine crackers', 18228, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('sandwich bun', 18353, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('sauerkraut', 11439, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('sausage', 1017063, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('sausage links', 1037063, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('scotch bonnet chili', 10011819, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('sea salt', 1012047, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('sea scallops', 10015172, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('seasoned bread crumbs', 18376, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('seasoned rice vinegar', 1032053, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('seasoned salt', 1042047, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('seasoning', 1042027, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('seasoning blend', 1032027, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('seeds', 93818, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('self-rising flour', 20129, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('semi sweet chocolate chips', 10019903, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('serrano chile', 11977, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('sesame oil', 4058, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('sesame seed hamburger buns', 10018350, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('sesame seeds', 12023, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('shallot', 11677, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('sharp cheddar cheese', 1031009, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('sheeps milk cheese', 1011019, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('shells', 11020420, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('sherry', 10114106, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('sherry', 10214106, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('sherry vinegar', 1012068, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('shiitake mushroom caps', 11238, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('short grain rice', 10120052, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('short pasta', 20499, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('short ribs', 10013149, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('shortbread cookies', 18192, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('shortcrust pastry', 10018338, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('shortening', 4615, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('shredded cheddar cheese', 1001009, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('shredded cheese', 1011026, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('shredded chicken', 1005114, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('shredded coconut', 12108, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('shredded mexican cheese blend', 1001251, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('shredded mexican cheese blend', 1251, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('shredded mozzarella', 1001026, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('silken tofu', 16161, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('sirloin steak', 23625, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('skim milk ricotta', 93630, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('skim vanilla greek yogurt', 99033, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('skin-on bone-in chicken leg quarters', 1005091, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('skinless boneless chicken breast halves', 1045062, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('skinless boneless chicken thighs', 5096, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('skinned black gram', 93718, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('slaw dressing', 43016, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('slaw mix', 10011109, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('slivered almonds', 10012061, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('smoked paprika', 1012028, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('smoked salmon', 15077, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('smoked sausage', 7916, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('smooth peanut butter', 16150, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('snapper fillets', 15101, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('snow peas', 11300, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('soda water', 14121, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('sour cream', 1056, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('sourdough bowl', 99169, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('sourdough bread', 10118029, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('soy milk', 16223, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('soy protein powder', 16122, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('soy sauce', 16124, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('spaghetti', 11420420, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('spaghetti squash', 11492, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('sparkling wine', 43155, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('spelt flour', 93823, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('spicy brown mustard', 1022046, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('spinach', 10011457, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('sprite', 14144, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('sprouts', 11001, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('squash', 10011485, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('sriracha sauce', 1016168, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('steaks', 23232, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('steel cut oats', 93695, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('stevia', 93628, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('stew meat', 10023618, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('stew vegetables', 11583, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('stock', 1006615, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('store-bought phyllo', 18338, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('stout', 93619, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('strawberries', 9316, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('strawberry jam', 10819297, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('strawberry jello', 10219172, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('stuffing', 18082, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('stuffing mix', 18081, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('sub rolls', 98940, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('sugar', 19335, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('sugar snap peas', 10011300, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('sugar syrup', 90480, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('sukrin sweetener', 99190, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('summer savory', 98961, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('summer squash', 11641, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('sunflower oil', 4584, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('sunflower seeds', 12036, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('sweet chilli sauce', 98962, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('sweet onion', 11294, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('sweet paprika', 1002028, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('sweet pickle juice', 93640, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('sweet pickle relish', 11945, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('sweet potato', 11507, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('sweet tea', 14355, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('sweetened coconut', 12109, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('sweetened condensed milk', 1095, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('sweetened shredded coconut', 12179, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('swiss chard', 11147, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('swiss cheese', 1040, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('taco seasoning mix', 2073, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('taco shells', 18360, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('tahini', 12698, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('tamari', 10116124, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('tapioca flour', 93696, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('tarragon', 2041, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('tart apple', 1029003, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('tea bags', 10111111, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('tequila', 10814037, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('teriyaki sauce', 6112, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('thai basil', 1012044, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('thai chiles', 11670, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('thai red curry paste', 93605, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('thick-cut bacon', 10310123, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('tilapia fillets', 15261, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('toast', 18070, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('toffee bits', 19383, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('tofu', 16213, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('tomatillos', 11954, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('tomato juice', 11886, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('tomato paste', 11887, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('tomato puree', 11547, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('tomato sauce', 11549, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('tomato soup', 6159, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('tomatoes', 11529, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('top blade steak', 13523, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('top round steak', 23636, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('Top Sirloin', 23584, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('tortilla', 18364, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('tortilla chips', 19056, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('triple sec', 14534, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('truffle oil', 1024053, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('tuna', 10015121, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('turbinado sugar', 19908, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('turkey', 5165, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('turkey breast', 5696, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('turkey kielbasa', 7955, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('turmeric', 2043, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('turnips', 11564, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('unbleached flour', 10020081, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('unsalted butter', 1145, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('unsmoked back bacon', 10130, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('unsweetened applesauce', 9019, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('unsweetened coconut milk', 12117, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('unsweetened shredded coconut', 10012108, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('vanilla bean', 93622, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('vanilla bean paste', 93813, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('vanilla essence', 1012050, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('vanilla extract', 2050, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('vanilla frosting', 10019230, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('vanilla instant pudding mix', 19206, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('vanilla protein powder', 99076, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('vanilla wafers', 18609, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('vanilla yogurt', 1119, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('vegan cheese', 93701, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('vegan chocolate chips', 98848, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('vegan margarine', 4673, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('vegetable broth', 6615, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('vegetable oil', 4513, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('vegetarian bacon', 16542, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('vermouth', 14132, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('vinaigrette', 4135, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('vinegar', 2053, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('vodka', 14051, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('walnuts', 12155, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('water', 14412, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('water chestnuts', 11590, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('water-packed tuna', 15121, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('watercress', 11591, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('watermelon chunks', 9326, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('wheat bran', 20077, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('wheat germ', 20078, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('whipped cream', 1054, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('whipped topping', 42135, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('whipping cream', 1001053, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('whiskey', 14052, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('white balsamic vinegar', 1012069, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('white bread', 18069, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('white cake mix', 18137, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('white cheddar', 1011009, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('white chocolate', 19087, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('white chocolate chips', 10019087, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('white onion', 10611282, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('white pepper', 2032, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('white whole wheat flour', 93824, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('white wine', 14106, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('white wine vinegar', 1002068, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('whole allspice berries', 1002001, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('whole chicken', 5006, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('whole coriander seeds', 2013, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('whole cranberry sauce', 9081, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('whole kernel corn', 11177, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('whole star anise', 1012002, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('whole wheat bread', 18075, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('whole wheat flour', 20080, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('whole wheat tortillas', 93675, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('whole-grain mustard', 1012046, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('wine', 14084, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('wine vinegar', 2068, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('winter squash', 10111485, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('won ton wraps', 10018368, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('worcestershire sauce', 6971, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('wraps', 10018364, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('xanthan gum', 93626, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('yeast', 18375, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('yellow bell pepper', 11951, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('yellow cake mix', 18144, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('yellow onion', 10511282, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('yogurt', 1116, NULL);
INSERT INTO ingredients_spoon (name, spoon_id, user_id) VALUES ('yukon gold potato', 10211362, NULL);